name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - source  # 确保这里与你的主分支名一致

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll Site
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BUILD }}
          publish_dir: ./_site
